### ISSUE TITLE
Add custom chooser for pick from gallery or camera option

### ISSUE THREAD

**Issue by salitosmbogz** [ronnieotieno/Ronnie-Image-Picker#3]
Could we have the option that merges the ability to pick from gallery and camera in one dialogue. Additionally allow customization of theme and option to choose from gallery only or camera only.

**Comment by ronnieotieno** [comment]
That's noted. Do you have some nice dialog design for that?

**Comment by salitosmbogz** [comment]
Thanks, I'll be sure to suggest any that I come across or up with.

**Comment by ronnieotieno** [comment]
Done, thanks for the suggestion. Please check latest release.
